### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'parentElement')

### ISSUE THREAD

**Issue by charlesmudy** [barakaally/unLayer2be#8]
Hello,

Nice work with the library, trying to pass a string of HTML file to this `email_design_json = Unlayer2be.fromHtml(html);` but I am getting the following error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'parentElement')
    at html2Unlayer.js:39:1
    at Array.map (<anonymous>)
    at Html2Unlayer.getColumns (html2Unlayer.js:36:1)
    at html2Unlayer.js:159:1
    at Array.map (<anonymous>)
    at Html2Unlayer.getDesign (html2Unlayer.js:153:1)
    at Function.__webpack_modules__../node_modules/unlayer2be/lib/src/utils/unlayer2be.js.Unlayer2be.fromHtml (unlayer2be.js:26:1)
    at FileReader.fr.onload (dashboard.js:273:1)`
    
    What could be the solution?

**Comment by barakaally** [comment]
> Hello,
> 
> Nice work with the library, trying to pass a string of HTML file to this `email_design_json = Unlayer2be.fromHtml(html);` but I am getting the following error:
> 
> `Uncaught TypeError: Cannot read properties of undefined (reading 'parentElement') at html2Unlayer.js:39:1 at Array.map (<anonymous>) at Html2Unlayer.getColumns (html2Unlayer.js:36:1) at html2Unlayer.js:159:1 at Array.map (<anonymous>) at Html2Unlayer.getDesign (html2Unlayer.js:153:1) at Function.__webpack_modules__../node_modules/unlayer2be/lib/src/utils/unlayer2be.js.Unlayer2be.fromHtml (unlayer2be.js:26:1) at FileReader.fr.onload (dashboard.js:273:1)`
> 
> ```
> What could be the solution?
> ```

Thanks for your feedback, working on resolving   bug!.

**Comment by charlesmudy** [comment]
Thank you @barakaally . Waiting for the push, you can do a test run with my HTML template here https://github.com/charlesmudy/responsive-html-email-template

**Comment by charlesmudy** [comment]
@barakaally how is it going and any update on this yet?
